<?php

namespace Database\Seeders;

use App\Models\Voter;
use Illuminate\Database\Seeder;

class TeacherSeeder extends Seeder
{
    public function run(): void
    {
        $voters = [
            [
                'voter_code' => '198611192020121008',
                'name' => 'ACHMAD SYARIF',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '199206032023212039',
                'name' => 'AHDA FANIA',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '199105112023211030',
                'name' => 'Anggara Elsa Bakhtiar',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197904252008011018',
                'name' => 'Arsudin',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '197305012006041018',
                'name' => 'Budiman',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '196804062017061001',
                'name' => 'Dalbini',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '199310212024212048',
                'name' => 'Depni Oktalia',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197212302023212002',
                'name' => 'Desi Yuliantini',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197510162008012010',
                'name' => 'Dewi Lasmy',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '199207192023212032',
                'name' => 'Dwi Asri Julianita',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197104232022211003',
                'name' => 'Eko Wardoyo',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197510042023212007',
                'name' => 'Elsi Simanjuntak',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '198002202008012016',
                'name' => 'Ferawati',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '199212202023211016',
                'name' => 'Firmansyah',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197604172008012027',
                'name' => 'Fitriah',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '197905192008012018',
                'name' => 'Gita Tri Narita',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '199305122023212041',
                'name' => 'Hana Yutika Prativi',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '198004172023211004',
                'name' => 'Heri Waluyo',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '198009112014121002',
                'name' => 'Imam Gunawan',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '197811172023212006',
                'name' => 'Isma Wahyuni',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '198207162023211014',
                'name' => 'Iwan Dina Candra',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197609282022211006',
                'name' => 'Kuswanto',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '196809082007012023',
                'name' => 'Liswati',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '197410042023211002',
                'name' => 'Mahrup',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '198612082023212039',
                'name' => 'Maulia Istiqomah',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197905112023211003',
                'name' => 'Michael Wadu Wila',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '199507112020121014',
                'name' => 'Mohammad Arief Rahman',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '198310102022211016',
                'name' => "Muamar Ma'ruf",
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '199405082023211010',
                'name' => 'Muhammad Nur Pirdaus',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '198005272023212014',
                'name' => 'Muslimaini',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197807122014122005',
                'name' => 'Nining Estuningsih',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '199212272023212037',
                'name' => 'Novita Desy Fatmawati',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197710262022212008',
                'name' => 'Octavia Permatasari',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '199404232024212063',
                'name' => "Rif'atu Nailis Sa'adah",
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '198002042022211004',
                'name' => 'Saparuddin',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '198903142022212003',
                'name' => 'Selvilia',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197103242006042015',
                'name' => 'Siti Maisaroh',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '197809152023212012',
                'name' => 'Sry Wahyuningsih',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '196609111990031005',
                'name' => 'Sugiman',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '197406302023211002',
                'name' => 'Sulistianto',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '196612062022212001',
                'name' => 'SURYATI S PD',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197004052023212003',
                'name' => 'Suwartini',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '196702131992031005',
                'name' => 'Tolibul Hadi',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '197003101994031005',
                'name' => 'Toto Sugiarto',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '198903022022212007',
                'name' => 'Tri Marfuah',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '196707171991032005',
                'name' => 'Triati Retno Wijayanti',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PNS',
                'status' => 'active',
            ],
            [
                'voter_code' => '197206032022212003',
                'name' => 'Yuni Purwanti Sari',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
            [
                'voter_code' => '197503252024211003',
                'name' => 'Zainal Abidin,s.ag',
                'role' => 'teacher',
                'class' => null,
                'position' => 'PPPK',
                'status' => 'active',
            ],
        ];

        foreach ($voters as $voter) {
            Voter::updateOrCreate(
                ['voter_code' => $voter['voter_code']],
                $voter
            );
        }
    }
}
