<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VotersClassXIISeeder extends Seeder
{
    public function run(): void
    {
        $voters = [
            [
                'voter_code' => '13888',
                'name' => 'AERO VEBRINA FADILLAH',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13889',
                'name' => 'AFIFA NOVITA SARI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13890',
                'name' => 'AHMAD ZHAFKY FATANSYAH',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13891',
                'name' => 'AIRA ANINDIA PUTRI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13892',
                'name' => 'AL BANI MAHESA HAZEL',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13893',
                'name' => 'ALAIKA BILQIS',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13895',
                'name' => 'AMELIA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13894',
                'name' => 'AMELIA PRATIWI MUNTHE',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13896',
                'name' => 'ANINDITA BUNGA AYUDIA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13897',
                'name' => 'ANNISA NURHILWA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13898',
                'name' => 'AUFA RIZAL RAIS',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13899',
                'name' => 'AURA JULIANA SADIN',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13900',
                'name' => 'AUREL NAFISHA MUHAMMAD SOLEH',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13901',
                'name' => 'AURORA CAMILLA NURDIN',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13902',
                'name' => 'BAITHAR AL MALAKI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13903',
                'name' => 'DEMAS HARYO DAMARINO',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13904',
                'name' => 'DHEA MATUZZAHRA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13905',
                'name' => 'DIAH FEBRIYANTI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13906',
                'name' => 'DIAN ANGGRAENI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13907',
                'name' => 'DJAHROH JULIA RAHMAWATI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13908',
                'name' => 'ELMO ALVIAN MEIDY',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13909',
                'name' => 'FAHRI RAHMAT DARMAWAN',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13910',
                'name' => 'FARSHA AULYA AVRIEL',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13911',
                'name' => 'FATHIYAH AT TABINA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13912',
                'name' => 'FATIMAH RAHMATUNISA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13913',
                'name' => 'FERISHA PUTRI ANOLA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13914',
                'name' => 'HADZIQ NAUFAL IRAWAN',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13915',
                'name' => 'INTAN DWI HAPSARI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13916',
                'name' => 'KAILA AULIA SIAGIAN',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13917',
                'name' => 'KAILA LAVINA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13918',
                'name' => 'KAYLA KHUMAIRAH PUTRI WANDANA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13919',
                'name' => 'KEYZHIA NUR SALSABILLA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13920',
                'name' => 'KHOIRULINA ARMADIZA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13921',
                'name' => 'LAKEISHA ARIANA PUTRI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13922',
                'name' => 'MAMORU VAAN OTSUKA ZAKI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13923',
                'name' => 'MELATI PUTRI CALISTA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13924',
                'name' => 'MOHAMMAD DIMAS PRAYOGO',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13925',
                'name' => 'MUHAMAD RIFAT ARKANANTA FIRDAUS',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13926',
                'name' => 'MUHAMAD RIZKY RAHMATUL AZIZ',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13927',
                'name' => 'MUHAMMAD NAJKHAN ARIFANI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13928',
                'name' => 'MUHAMMAD RAYHAN ASSYAUQI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13929',
                'name' => 'NADYA INTAN KIRANA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13930',
                'name' => 'NAILA TALITA SAKHI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13931',
                'name' => 'NASYA ANAYA DWI PUTRI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13932',
                'name' => 'NASYA TITIANI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13933',
                'name' => 'NAZLI FARHAN ABDULLAH TARMUM',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13934',
                'name' => 'NOVIANI RAHMA DEWI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13935',
                'name' => 'NURUL HOTIMAH',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13936',
                'name' => 'PRIMA JOHAN NARARYA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13937',
                'name' => 'PUAN GENDIS CAHAYA RIANTI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13938',
                'name' => 'RAHFA ALFIANSYAH',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13939',
                'name' => 'RAISA AKMALIA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13940',
                'name' => 'RAYHAN ARSENIO',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13941',
                'name' => 'REKTIVIANA JASWIKA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13942',
                'name' => 'RETNO MANSYLLA DEWI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13943',
                'name' => 'RIVANNO APRIANSYAH',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13944',
                'name' => 'RIZKY AFREZHAN',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13945',
                'name' => 'RIZKY FATILLAH RADITYA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13946',
                'name' => 'RUTH URSULA DIMUKRIS',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13947',
                'name' => 'SAFA IBNU AWALI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13948',
                'name' => 'SALSATUL AZIZAH CAHYANI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13949',
                'name' => 'SEPTI DIAN MARIFI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13950',
                'name' => 'SHAFIRA KAYLA RAHMADANI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13951',
                'name' => 'SITI AISIYAH RAMADHANI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13952',
                'name' => 'SUKMA TRI WAHYUNI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13953',
                'name' => 'SYAFIRA ANINDITA WIRANSYAHTI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13954',
                'name' => 'TANIA KHAIRUNNISA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13955',
                'name' => 'TASYA OLIFIA ASSYAFAH',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13957',
                'name' => 'TIARA NURAINI OKTAVIA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13956',
                'name' => 'TIARA SEFIA RIMAWATI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13958',
                'name' => 'VIRNIE BALKIS SAVITRI',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13959',
                'name' => 'WULAN PANULUH SUKMA',
                'role' => 'student',
                'class' => 'XII AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13960',
                'name' => 'ADINDA SALSABILA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13961',
                'name' => 'ADZIRA ELSA NALISA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13962',
                'name' => 'ALFIRA RIZKA PARADILLA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13963',
                'name' => 'ALINA DWI AQILLA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13964',
                'name' => 'ANANDA JULIANA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13965',
                'name' => 'ARDA AL KAUTSAR',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13966',
                'name' => 'ARVID HERLYANTO',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13967',
                'name' => 'ARWA ABIYAH',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13968',
                'name' => 'CHEERY ZORA ZETIRA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13969',
                'name' => 'DEANDRA ANANDA FATIHA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13970',
                'name' => 'DIMAS ADRIANTO',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13971',
                'name' => 'DIVA DEA CHARITY',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13972',
                'name' => 'DWI SABILA ROZAK',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13973',
                'name' => 'FHATANSHA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13974',
                'name' => 'KARINA BEE AISYA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13975',
                'name' => 'KHANZA SALSABILA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13976',
                'name' => 'KINARA PUTRI RAESMAWATI',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13977',
                'name' => 'KIRANA LARASATI',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13978',
                'name' => 'MUHAMMAD AL-FATHAN PRATAMA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13979',
                'name' => 'MUHAMMAD HASBIE ADILA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13980',
                'name' => 'MUHAMMAD KIVLAN JUNIANS',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13981',
                'name' => 'NAJMAH QARRIS SHAFIRA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13982',
                'name' => 'NUR FARIDA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13983',
                'name' => 'PUTRI CAHYA INDIANI',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13984',
                'name' => 'PUTRI ZUHROTUL INANSYAH',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13985',
                'name' => 'RAMDAN SAPUTRA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13986',
                'name' => 'RAUF GUTAMA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13987',
                'name' => 'REYNA PUTRI RAMADANI',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13988',
                'name' => 'RIFQI APRIANSYAH',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13989',
                'name' => 'SCEHAN BILQIES SABRINA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13990',
                'name' => 'SITI FATIMAH AZAHRA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13992',
                'name' => 'SRI NUR LAILA',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13993',
                'name' => 'SYAUQI HAZAMI',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13994',
                'name' => 'WAZHA ROSIANA SETYAWAN',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13995',
                'name' => 'YANAH',
                'role' => 'student',
                'class' => 'XII LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13996',
                'name' => 'ADHITYA AZKA AS-SHIDIQI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13997',
                'name' => 'AFAF HILWA NAJMAYA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13998',
                'name' => 'AKBAR ARDY PRATAMA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '13999',
                'name' => 'ALISHA DANELLA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14000',
                'name' => 'ALZENA LANIKA HIDAYAT',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14001',
                'name' => 'ANANDA ASRI ASTRIANA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14002',
                'name' => 'ANANDA TRI FEBIYANTI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14003',
                'name' => 'ANGGITA KHOIRILIA ROHMAT',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14004',
                'name' => 'ANISA NUR OKTAPIANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14005',
                'name' => 'ANNISA PUTRI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14006',
                'name' => 'AQEELA BUNGA KIRANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14007',
                'name' => 'ARSYIKA SAHLA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14008',
                'name' => 'ARUM WULANDARI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14009',
                'name' => 'AURA DWI AGUSTIN',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14010',
                'name' => 'AZHARIAH AZ ZAHRA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14011',
                'name' => 'AZKA MANDALA P',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14013',
                'name' => 'CARRISA AZ ZAHRA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14014',
                'name' => 'CHANDRA ARIYO GEMILANG',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14015',
                'name' => 'CHANDRA DWI PRASETYO',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14016',
                'name' => 'CHELSEA HOT TUA SIMAMORA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14017',
                'name' => 'CINTA LESTARI PUTRI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14018',
                'name' => 'DALILAH',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14019',
                'name' => 'DELA SIVIKA PUSPITA NINGRUM',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14020',
                'name' => 'DESVIANA PUTRI HANDAYANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14021',
                'name' => 'DINAR JIHAN ANGGREYANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14022',
                'name' => 'ECHA QURRATUS SYFA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14023',
                'name' => 'EGA MAULANA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14024',
                'name' => 'FAIZA NAYLA IRYANDA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14025',
                'name' => 'FANNY FALIHAH',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14026',
                'name' => 'FARHAH SHALEHAH ZAMANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14027',
                'name' => 'FARHAINI SALSABILLAH',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14028',
                'name' => 'FEBRIANTI RISKA SAVITRI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14029',
                'name' => 'FHATIA AL ZAHRA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14030',
                'name' => 'HANIF RIZKY PRATAMA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14031',
                'name' => 'HAURA BINTANG MAHARANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14032',
                'name' => 'IMA NURAINY IKHSAN',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14033',
                'name' => 'IRVI ISTIANTI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14460',
                'name' => 'IKSAN JONATHAN PRAYOGA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14034',
                'name' => 'IZMIANAS',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14035',
                'name' => 'JINGGA NAURA AULIA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14036',
                'name' => 'KAILA PUTRI HIDAYAT',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14037',
                'name' => 'KARUNIA MAULIDANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14038',
                'name' => 'KEISYA DWI FATIKA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14039',
                'name' => 'KEYLLA SASMITA STIANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14040',
                'name' => 'KEZIA DYA NADIRA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14041',
                'name' => 'KHANZA ARIFAH ANDANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14042',
                'name' => 'KIARA PUTRI YUNIAR',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14043',
                'name' => 'LULU LUTHFIYYAH FAUZAN',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14044',
                'name' => 'MARSHA MAULIDYA PUTRI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14045',
                'name' => 'MUHAMAD IZZAT HERMAWAN',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14046',
                'name' => 'MUHAMAD ZIDAN',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14048',
                'name' => 'MUHAMMAD FACHRI ADZANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14047',
                'name' => 'MUHAMMAD RIZKY RAMDHAN',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14049',
                'name' => 'NADIN KAYLA MARLI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14050',
                'name' => 'NAIILA INAS QAMRA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14051',
                'name' => 'NUR AISYAH FITHRIYYANI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14052',
                'name' => 'NUR AZIZAH KURNEASIH',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14053',
                'name' => 'NUR SABILLA FATIHA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14054',
                'name' => 'NURRIZKY KAMILA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14055',
                'name' => 'NURUL MUFIDAH',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14056',
                'name' => 'RAHMAH APRIANTI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14057',
                'name' => 'RAZITA DHIYAA SAFURA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14058',
                'name' => 'RINJANI SYIFA ANINDITA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14059',
                'name' => 'RIZKY MAULANA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14060',
                'name' => 'SAISA NABILLA KHOIRUNNISA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14061',
                'name' => 'SASKIA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14062',
                'name' => 'SAVIRA FITRI KHAIRUNISA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14063',
                'name' => 'SELVIANA LESTARI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14064',
                'name' => 'VERI ANGKASA PUTRA',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14065',
                'name' => 'WULAN TRY NENGSIH',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14066',
                'name' => 'YUZRIYA INDAH PRATIWI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14067',
                'name' => 'ZAHRAH RIZKA NURAENI',
                'role' => 'student',
                'class' => 'XII MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14068',
                'name' => 'AGESTYA RISQIANA DARMAWAN',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14069',
                'name' => 'ALFAREZA DWI OKTORA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14070',
                'name' => 'ANJANI NURAPRILIA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14071',
                'name' => 'ANNISA FAUZIAH',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14072',
                'name' => 'AURELIA DEWA PRAWITA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14073',
                'name' => 'AVIF PATHUR HIDAYAT',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14074',
                'name' => 'AZRA DEFSA SALSABILA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14075',
                'name' => 'BALQIS AULIA ANANDA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14076',
                'name' => 'CINTYA RAHMAN',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14077',
                'name' => 'DENANDA DENDRA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14078',
                'name' => 'DHENIS SONYA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14079',
                'name' => 'DHIA FAUZAN AL KAMIL',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14080',
                'name' => 'DIO IBRAHIM MOVIK',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14081',
                'name' => 'DUWI PURNOMO',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14082',
                'name' => 'FATHIR AULADI RIZQI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14083',
                'name' => 'FEBI FEBRIYANTI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14084',
                'name' => 'FUJI ZALVA AZIZAH ROCHMAH',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14085',
                'name' => 'GILANG ILHAM IBRAHIM',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14086',
                'name' => 'HIKMAL ALIF ARDIAN',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14087',
                'name' => 'IBRAHIM NUR SYARIF',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14088',
                'name' => 'MUHAMAD RAFKA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14089',
                'name' => 'MUHAMMAD FACHRI RAHMADI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14090',
                'name' => 'MUHAMMAD FATHIR BAIHAQI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14091',
                'name' => 'NUR LEILA SANJAY',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14092',
                'name' => 'PEMI ALENTA SILABAN',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14093',
                'name' => 'RAUL YUSUF AKBAR',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14094',
                'name' => 'REVAN DWI ANGGARA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14095',
                'name' => 'RISFA PURNAMASARI RAMADHANIYAH',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14096',
                'name' => 'SANWA RAMADHAN KURNIAWAN',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14097',
                'name' => 'SAYIDAH NAYLA RAMADHANI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14098',
                'name' => 'SHEILA AIRA PUSPITASARI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14099',
                'name' => 'TIARA TALITA PUTRI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14100',
                'name' => 'WIDYA MELINDA',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14101',
                'name' => 'WILDHAN SHAQUILLE UMAMMI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14102',
                'name' => 'ZASKYA AULIA ADAM',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14103',
                'name' => 'ZULFA AFIFAH RAMADHANI',
                'role' => 'student',
                'class' => 'XII BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14104',
                'name' => 'ADI LINGGA PRATAMA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14105',
                'name' => 'AHMAD ZIYAD RADYATMA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14106',
                'name' => 'AKILA INAYA ARHAMI',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14107',
                'name' => 'ALEA NAILA ZALFA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14108',
                'name' => 'ALEXA NOVANDREA PUTRA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14109',
                'name' => 'ALZENA HENDRYANNA FARRAS',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14110',
                'name' => 'ANANDA ABIYYU SAQIB',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14111',
                'name' => 'BAGAS PRATAMA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14112',
                'name' => 'BAROQAH GIESLATIF HERIYANTO',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14113',
                'name' => 'DAFFA ANANDA PUTRA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14114',
                'name' => 'DELFINA AZARIA ANDINI',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14115',
                'name' => 'FARRIZQI ICHSAN MAULANA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14116',
                'name' => 'FAUZAN AKBAR',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14117',
                'name' => 'FILDZA KAMILA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14118',
                'name' => 'KAYYIS FAQIH AMANU',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14119',
                'name' => 'KEISHA ANINDYA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14120',
                'name' => 'KEYZA ALZENA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14121',
                'name' => 'LULU MAZAYA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14122',
                'name' => 'MARIA HANIFAH',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14123',
                'name' => 'MARSYA ANANDITA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14124',
                'name' => 'MUHAMAD NAZRIL ALFAHRI',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14125',
                'name' => 'MUHAMMAD JUSTIN WANG',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14126',
                'name' => 'MUHAMMAD NIKO ARDIANSYAH',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14127',
                'name' => 'NAUFAL NUR FIKRI',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14128',
                'name' => 'PUTRA HAFIDZ ARDIANTO',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14129',
                'name' => 'RADEN RORO ANNISA ANINDYA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14130',
                'name' => 'REZA FADILLAH',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14131',
                'name' => 'SALWA AMELIA FITRIANA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14132',
                'name' => 'SANIA CALISTA PUTRI',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14133',
                'name' => 'SAYYIDINA RHAFA PUTRA HIDAYAT',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14134',
                'name' => 'SYIFA SHAFIYYAH',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14136',
                'name' => 'VANIA SASIKARINA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14137',
                'name' => 'VERINA SASIKIRANA',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14138',
                'name' => 'YUWANIZA GLADIES',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14139',
                'name' => 'ZAHIRA ANANDA ABIDIN',
                'role' => 'student',
                'class' => 'XII BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14140',
                'name' => 'ABU ABDILLAH MUHYIDDIN AL QORRIB',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14141',
                'name' => 'ABYAN RAZIN ADRIANSYAH',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14142',
                'name' => 'ADITYA SAPUTRA',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14143',
                'name' => 'AFGAN RAMADHAN',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14144',
                'name' => 'AHMAD ALIFFANSYAH',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14145',
                'name' => 'AIDHIL FAHIM MUBARRAQ',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14146',
                'name' => 'ALTAF AZKA AVIANTARA',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14147',
                'name' => 'ALVARO GERALDY',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14148',
                'name' => 'ALVARO RAKA PRATAMA',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14149',
                'name' => 'ANANDA WIMAULANA',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14150',
                'name' => 'AZZAM FADHLAN EFRIZAL YUSUF',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14151',
                'name' => 'BAGAS CHANDRA NIRVANA',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14152',
                'name' => 'DAFFA YUMNA ZUBAIR',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14153',
                'name' => 'ELMALIQ SAFATORIQ AKBAR',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14154',
                'name' => 'FAHRI DWI PRASETYO',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14155',
                'name' => 'FATHI RIZKIANSYAH',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14156',
                'name' => 'GAZHY ARKANA PRAMUDITO',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14157',
                'name' => 'HAFIEZ SHADRY',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14158',
                'name' => 'HAFIIZH MAULANA SOHIBBULL WAFFA',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14159',
                'name' => 'HAFIZH RAFA RADITIAN',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14160',
                'name' => 'JARIS YULIAN ADITYA',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14161',
                'name' => 'KAREL KORNELIUS',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14162',
                'name' => 'MAHARDIKA BINTANG RAMADHAN',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14163',
                'name' => 'MARCHIANO VALEN SAVANO',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14164',
                'name' => 'MARVELL ARRAYA KUSNADI',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14165',
                'name' => 'MUHAMAD BINTANG JUNIOR',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14166',
                'name' => 'MUHAMMAD ALI NARAHANSYAH',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14167',
                'name' => 'MUHAMMAD FAQIH MUQODDAM',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14168',
                'name' => 'NEEVAXIIUS KENZIE',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14169',
                'name' => 'NEINA KHAIRANI',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14170',
                'name' => 'RADEN RICHWAN RAYINANDA AFANDI',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14171',
                'name' => 'REIVAN ADHITYA MAULANA',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14172',
                'name' => 'WAFI AKMALUZZUHAIR',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14173',
                'name' => 'ZEINI ASWIN RANGKUTI',
                'role' => 'student',
                'class' => 'XII REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
        ];

        foreach ($voters as $voter) {
            DB::table('voters')->updateOrInsert(
                ['voter_code' => $voter['voter_code']],
                $voter
            );
        }
    }
}
