<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VotersClassXISeeder extends Seeder
{
    public function run(): void
    {
        $voters = [
            [
                'voter_code' => '14174',
                'name' => 'AHMAD FARHAN',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14175',
                'name' => 'AISYAH BALQIS',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14178',
                'name' => 'ALVIS FAUZI JUNIAR',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14179',
                'name' => 'ALZAHRA NUR FATIMAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14182',
                'name' => 'ANNASYA DWI OCTAVIA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14183',
                'name' => 'ANNISA FITRIAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14186',
                'name' => 'ATHALIA PUTRI RAMADHANI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14187',
                'name' => 'AYU CITRA CHINTAMI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14190',
                'name' => 'CARISSA PUTRI ANDIRA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14191',
                'name' => 'CIENLYANA MAHARANI PRIYONO',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14194',
                'name' => 'DIVA SHAHADA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14195',
                'name' => 'EKA PUTRI WULANDARI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14198',
                'name' => 'FEBY RIZKI SUSANTI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14199',
                'name' => 'GAYATRI AYU APRILIA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14202',
                'name' => 'HARUMI BUMI WIJAYA PUTRI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14203',
                'name' => 'IASHA JASMINE SALSABIELLA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14206',
                'name' => 'KEISHA FARRAS NAURASYIFA AN-NAAFIYAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14207',
                'name' => 'KEISYA NURUZAHRA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14210',
                'name' => 'MARWA TAKBIRUL AULIA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14211',
                'name' => 'MARYEMAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14214',
                'name' => 'MOHAMAD FATKHAN RAMADHAN',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14215',
                'name' => 'MU\'AZAROH AL JAMILA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14218',
                'name' => 'MUHAMMAD ADLY ALFATTAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14219',
                'name' => 'MUHAMMAD FARREL ALFA RIZIQ',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14222',
                'name' => 'MUHAMMAD PANDU ARYASENA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14223',
                'name' => 'MUHAMMAD RAFI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14463',
                'name' => 'NATASYA JULIANA RISMA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14227',
                'name' => 'PUTRI KIRANA RAMADHANI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14228',
                'name' => 'QUEENA ALIEFA MAULANI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14231',
                'name' => 'RAKHA YAZDAN HAFIZH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14234',
                'name' => 'RIFKAR PERMATASARI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14235',
                'name' => 'SAFA TAKBIRUL AULIA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14238',
                'name' => 'SEKAR AYU NINDITA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14239',
                'name' => 'SITI NAZMA ZULIANA SANKAR',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14242',
                'name' => 'THOMY AHMAD FAKHRI ZAIN',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14243',
                'name' => 'TRIANDAH PUTRI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14176',
                'name' => 'AJENG SANDIRA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14177',
                'name' => 'ALFIAN MUFLIH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14180',
                'name' => 'AMANDA AULIA SYAHRANI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14181',
                'name' => 'ANDIRA CINTA NURAZIZAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14184',
                'name' => 'ANZALNA PUTRI QYARA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14185',
                'name' => 'ARYSTA SIERA RACHIE',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14188',
                'name' => 'AZKYA ZAHIRAH SOFYAN',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14189',
                'name' => 'BELLA AMALIA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14192',
                'name' => 'DESTI NURHAFIZAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14193',
                'name' => 'DEVINA SAHRANI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14196',
                'name' => 'FARAS FATHURRAHMAN SYATARI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14197',
                'name' => 'FAUZAN HADI SYAHPUTRA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14200',
                'name' => 'GENDIS ROBIATUL AWALIYYAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14201',
                'name' => 'GITA ANJANI SAPUTRI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14204',
                'name' => 'ILHAM NUR RIFAI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14205',
                'name' => 'JESSY AISAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14208',
                'name' => 'KEYSHA ALMIRA HARDIANSYAH',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14209',
                'name' => 'MARIA LUCIA ARE LAMADIKE',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14212',
                'name' => 'MELINDA SAFITRI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14213',
                'name' => 'MIFTAH AWALUDIN',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14216',
                'name' => 'MUHAMAD FAKHRI ALWI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14217',
                'name' => 'MUHAMAD SYAFIK ANNURIS',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14220',
                'name' => 'MUHAMMAD FATHIR ERNANDA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14221',
                'name' => 'MUHAMMAD HABLIL JIDDA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14224',
                'name' => 'MUNA HAMIDAH HANAN',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14225',
                'name' => 'NAFISA ASKHA WALIDAYNI IKHSANA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14226',
                'name' => 'NAZWA NUR AINI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14229',
                'name' => 'RADISHA NAYA PUTRI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14230',
                'name' => 'RAFFEL PUTRA JAYA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14233',
                'name' => 'REZIFO KHAIFADLI',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14236',
                'name' => 'SALMA ANJELIKA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14237',
                'name' => 'SARAH AMIRA MEYDA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14240',
                'name' => 'STEFANI OCTA DESILVIA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14241',
                'name' => 'TANIA OKTAVIANI VIRGIAWAN',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14244',
                'name' => 'ZASKIA ALIEFA OCTAVIA',
                'role' => 'student',
                'class' => 'XI AKUNTANSI 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14247',
                'name' => 'ABYAN SYAFIQ KHALQILLAH',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14248',
                'name' => 'AHMAD RIZQI RAMADHAN',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14249',
                'name' => 'AINAA\'UL RISTYANA ZAHRA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14250',
                'name' => 'ALYA FATIKAH KHALISYAH',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14251',
                'name' => 'AMIRAH RAISYA PUTRI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14252',
                'name' => 'ANNISA DWICANDRA OKTAVIANI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14253',
                'name' => 'ARINI DWIASTUTI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14254',
                'name' => 'AUDYE KHOI NOER',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14255',
                'name' => 'AULIA NURHAFIZAH',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14256',
                'name' => 'CHAIRUNNISA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14257',
                'name' => 'CLARISSA PUTRI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14258',
                'name' => 'CLAUDIA SHINTA XAVINA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14259',
                'name' => 'DONITA SYAHPUTRI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14260',
                'name' => 'HAIFA ZHILYA AVIKA ROFIQ',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14261',
                'name' => 'ILENNE ROSSYA EMMELYA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14262',
                'name' => 'INEZA NOVIA ARINI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14263',
                'name' => 'KAZIO MUHAMMAD AL AYUBI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14264',
                'name' => 'KHANZA NAZIHA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14265',
                'name' => 'KHEYSA AULIA PUTRI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14266',
                'name' => 'MAULIDYA DWI RIZQIA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14267',
                'name' => 'MUHAMAD AUFAH',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14268',
                'name' => 'MUHAMMAD LUKMAN FARID RIZQI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14269',
                'name' => 'NAUFAL RISKI AHNAF',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14270',
                'name' => 'NAZWA AULIA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14271',
                'name' => 'NUR WAHIDAH',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14272',
                'name' => 'PUTRI AULIYA RAHMA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14273',
                'name' => 'PUTRI WIBOWO',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14274',
                'name' => 'RADITYA REVAN SYAHREZHA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14275',
                'name' => 'RAISHA RAMADHANTI CAHYA SYIFA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14276',
                'name' => 'RIZKY DWI RADHITYA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14277',
                'name' => 'SAFINA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14278',
                'name' => 'TIARA AISYAH JUNAEDI',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14279',
                'name' => 'TIARA NURJAISYAH',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14280',
                'name' => 'VEVITA SAYYIDATUNISSA SURAHMAN',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14281',
                'name' => 'ZAHRA FAUZIYYAH',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14282',
                'name' => 'ZASKIA MEGA',
                'role' => 'student',
                'class' => 'XI LAYANAN PERBANKAN SYARIAH',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14461',
                'name' => 'AHMAD MUZAKI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14462',
                'name' => 'AIRA NUR OKTAVIANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14285',
                'name' => 'ALIFYA RAMADHANY',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14286',
                'name' => 'ALMEIRA KIRANA PUTRI SANTOSO',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14289',
                'name' => 'ANNISA DEVI TALITA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14290',
                'name' => 'ANNISA\' NOVIA RAMADHANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14293',
                'name' => 'ASTRID DWI OKTAFIANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14294',
                'name' => 'AULIA RAMADANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14297',
                'name' => 'AVISA APRILIYANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14298',
                'name' => 'BILQIIS AADILAH',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14301',
                'name' => 'DINA AGUSTINA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14302',
                'name' => 'DINDA MULYASARI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14305',
                'name' => 'FAIRUZ AKBAR CHAIDIR',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14306',
                'name' => 'FAIZ RAFSANJANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14309',
                'name' => 'HALIMATUSSA\'DIAH',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14310',
                'name' => 'HANDHITA SYAMUHARA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14313',
                'name' => 'KHAYIRAH TALITA SAKHI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14314',
                'name' => 'KIRANA PUTRI WIJAYA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14317',
                'name' => 'MENDY ALVIANNO',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14318',
                'name' => 'MEYLANI AL MEYRA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14321',
                'name' => 'MUHAMMAD NOER HOLIS PAUSI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14323',
                'name' => 'NADHIRAH KHAIRUNNISA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14325',
                'name' => 'NAILUL MANAL SALWANA RUSNAWATI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14326',
                'name' => 'NASYA AZZAHRA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14329',
                'name' => 'NAZILA NAURIEL',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14330',
                'name' => 'NAZWA AFRILLA NURAHMI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14333',
                'name' => 'RAFIN PUTRA PRAWARA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14334',
                'name' => 'RICHA AYU RAMADHANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14337',
                'name' => 'SALSABIL SAAHIRAH',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14338',
                'name' => 'SELFIA RIZKI NURAINI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14340',
                'name' => 'SHILVIA MAHARANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14341',
                'name' => 'SITI FATHONAH NUR AZIZAH',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14344',
                'name' => 'TIFANNY JULIANTI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14345',
                'name' => 'TRIAS DANDY HERNITO',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14348',
                'name' => 'YASHINTA MARYAM',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14349',
                'name' => 'YULIA MARLIANA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 1',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14283',
                'name' => 'ALECIA AQSHA MILANO',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14284',
                'name' => 'ALEKA DWI OKTANATA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14287',
                'name' => 'ANDRA URIAGI PRASETHIO',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14288',
                'name' => 'ANISYA DWI AGUSTIN',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14291',
                'name' => 'ARISKA MEYRANI PUTRI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14292',
                'name' => 'ARSYAH DWINDA PUTRI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14295',
                'name' => 'AULIA ZIFFARA MAULIDA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14296',
                'name' => 'AUREL NATHASA FAUZIAH',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14299',
                'name' => 'CHESLYN OZORA BANUREA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14300',
                'name' => 'CHIKA AQUILLA SALSABILA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14303',
                'name' => 'DIVYATUL HUSNA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14304',
                'name' => 'DZIKRAFHIYA MALAYUDZIHNI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14307',
                'name' => 'FAWWAZ NUR SYAFIQ',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14308',
                'name' => 'HAFIDZATUL HANAN',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14311',
                'name' => 'HARIS ADLI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14312',
                'name' => 'JIHAN ZAHIRA TALITA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14315',
                'name' => 'LIVIA FEBRIYANTI SURYA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14316',
                'name' => 'MAWAR DAFILA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14319',
                'name' => 'MUHAMMAD ARBA ARVANSYAH',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14320',
                'name' => 'MUHAMMAD FAHMI ALFARIZ',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14322',
                'name' => 'MUHAMMAD NOVAL FASYA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14324',
                'name' => 'NADIVA SYAQINA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14327',
                'name' => 'NATASIA FEBIANTI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14328',
                'name' => 'NAY SHEILA CAMALYA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14331',
                'name' => 'NURHAYATI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14332',
                'name' => 'RAFA ALFARIZI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14335',
                'name' => 'SAHAL MUHAMMAD KAMAL',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14336',
                'name' => 'SALLY CARISSA NOVIYANTI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14339',
                'name' => 'SEPTIAWAN NUR RAMADHAN',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14350',
                'name' => 'SHIFA TUNISA RAHMAWATI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14342',
                'name' => 'SITI KHUMAIROH',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14343',
                'name' => 'TARA SHALBIYYAH KAWIDIANTI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14346',
                'name' => 'VARRADILLA PUTRI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14347',
                'name' => 'WIDIYATI LATIFAH',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14351',
                'name' => 'ZALFA SALSABILLA',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14352',
                'name' => 'ZASKIA PUTRI RHAMADANI',
                'role' => 'student',
                'class' => 'XI MANAJEMEN PERKANTORAN 2',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14353',
                'name' => 'ADINDA PUTRI',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14354',
                'name' => 'AHMAD KHADAFY',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14355',
                'name' => 'ALFIAN ASHOBIRIN',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14356',
                'name' => 'AMANDA SAFINATUNNAJAH',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14357',
                'name' => 'ANGGIT SALSABILA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14359',
                'name' => 'ANNISA TRI HANDAYANI',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14360',
                'name' => 'CHARISA HAJMANA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14464',
                'name' => 'CHERYL NOORALYA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14361',
                'name' => 'DAFA WILDAN YUSUF',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14362',
                'name' => 'DAVINA MARSHA PANGARIBUAN',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14363',
                'name' => 'DIMAS MAULANA FEBRIANSYAH',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14364',
                'name' => 'INDAH PUTRI BENZYUMA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14365',
                'name' => 'ISMI AINUR FEBRIAN',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14366',
                'name' => 'KHAEDAR ALI FACHMI BACHMID',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14367',
                'name' => 'KHAYRANI ABADAN',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14368',
                'name' => 'LAURAINE JUCIKA SONGKILAWANG',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14369',
                'name' => 'MUHAMAD FAIZ',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14370',
                'name' => 'MUHAMMAD RIDHO IRSYAD',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14371',
                'name' => 'NAURA MEYCAHYANA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14372',
                'name' => 'NIZRIN FAUZIAH',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14374',
                'name' => 'NURZANAH SAFITRI',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14375',
                'name' => 'OLIVIA ARIESTA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14376',
                'name' => 'PUTRICIA MAHARANI',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14377',
                'name' => 'RADEN DANENDRA MAHARDIKA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14378',
                'name' => 'RAISSA AZ ZAHRA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14379',
                'name' => 'RAISYA ZALFA SADINA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14380',
                'name' => 'RASHYA AZKIA CAHYA SAPUTRI',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14381',
                'name' => 'SARAH REGINA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14382',
                'name' => 'SHAFA NOVITA AROFAH',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14383',
                'name' => 'SYAFA ALDIRA NUR RIZKIA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14384',
                'name' => 'SYALFA AMANDA APRILYANTI',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14385',
                'name' => 'WANDA FITRIANI',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14386',
                'name' => 'YASMIN ARUM DAMAYANTI',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14387',
                'name' => 'ZAFARA AULIA',
                'role' => 'student',
                'class' => 'XI BISNIS RETAIL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14388',
                'name' => 'ADINDA FEBRIANI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14389',
                'name' => 'AHMAD ZAIDAN',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14390',
                'name' => 'AISY SHOFI FIRDAUS',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14391',
                'name' => 'ARYA FIRMANSYAH',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14392',
                'name' => 'ASYILA ILMI RAMADHANI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14393',
                'name' => 'AZTYN NADA FORTUNA',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14394',
                'name' => 'DEWI SITA ANDINI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14395',
                'name' => 'DZASKHIA RAHMA',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14396',
                'name' => 'EKO ADI SAPUTRA',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14397',
                'name' => 'ERRY CINDY SUHARYADI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14398',
                'name' => 'FADLAN DZILIKRAM',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14399',
                'name' => 'FAHAR MAULANA USMAN',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14400',
                'name' => 'FASHA KAMIL IHSAN',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14401',
                'name' => 'FATHIYAH MARWAH',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14402',
                'name' => 'FRIZKA ZAHRA AMELIA',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14403',
                'name' => 'GRACE ANGELA WADU WILA',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14404',
                'name' => 'HASBI AL FAHTIR',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14405',
                'name' => 'KIRANI AISYAH PUTRI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14406',
                'name' => 'MOHAMMAD JABAL THORIQ RAMADHAN',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14407',
                'name' => 'MOHAMMAD RIO FEBIAN',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14408',
                'name' => 'MUHAMAD AZRIEL HISAHITO',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14409',
                'name' => 'MUHAMMAD ALIF ARSLAN',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14410',
                'name' => 'NA\'ILAH PUJA ASTUTI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14411',
                'name' => 'NARAYA AZAHRA',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14412',
                'name' => 'NOVA ALIZA',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14413',
                'name' => 'RAFASHA RIZKI SOFYAN',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14414',
                'name' => 'RAYHANA AZKA NAFISAH',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14415',
                'name' => 'RIVANO AZUAN VERIZQO',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14416',
                'name' => 'SAFARINA FEBRIANTI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14417',
                'name' => 'SASKIA RAMADHANI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14418',
                'name' => 'SERGIO RAMOS PARTOGI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14419',
                'name' => 'SERLYLELITA PHASA PUTRI SIREGAR',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14420',
                'name' => 'SHABRINA GHASSANI FRADHANA',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14421',
                'name' => 'SYAIFA DINA RAMADHANI',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14422',
                'name' => 'ZAHARA YAFFA YUSUF',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14423',
                'name' => 'ZAHKIA AHLYA QORY',
                'role' => 'student',
                'class' => 'XI BISNIS DIGITAL',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14424',
                'name' => 'ABIMANYU WISNU MUKTI',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14425',
                'name' => 'AHMAD PUTRA RAMADHAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14426',
                'name' => 'AHMAD RAFFA HAFIDZHIAN SYAH',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14427',
                'name' => 'AHMAD RIFAQQI AL FARUQI',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14428',
                'name' => 'AHMAD ROMMY QURNIAWAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14429',
                'name' => 'ALFIN DZAKY MUMTAZAM',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14430',
                'name' => 'AZHAHIR ALTHAF FAUZTIAN ZHABNI',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14431',
                'name' => 'AZIZAH DZAKIYAH KHAIRIYAH',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14432',
                'name' => 'BAHTRA AJI AKBAR RAMADHAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14750',
                'name' => 'DEBBY LAURA PUTRI',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14434',
                'name' => 'FAISHAL FAWWAAZ',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14435',
                'name' => 'FATIHUDDIN FAWWAZ',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14436',
                'name' => 'FERO SAFA WAHYUDI',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14438',
                'name' => 'GILANG DIANTA RAMADHAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14439',
                'name' => 'HASBI IMRAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14440',
                'name' => 'JASMINE MONICA HARIS',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14441',
                'name' => 'KAYSIA PUTRI ARIFAH',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14442',
                'name' => 'LINGGA WIRYA PRAYATA',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14443',
                'name' => 'MARSYA RANJANI',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14444',
                'name' => 'MUCHAMMAD DIKI PAUZAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14445',
                'name' => 'MUHAMMAD ALFI MASRUR KURNIANTO',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14446',
                'name' => 'MUHAMMAD ALMAHDI',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14447',
                'name' => 'MUHAMMAD ATHAR FAZHAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14448',
                'name' => 'MUHAMMAD DAFA ALFIAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14449',
                'name' => 'MUHAMMAD FARDHAN HELMIANSYAH',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14450',
                'name' => 'MUHAMMAD ROCHIMULOH',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14451',
                'name' => 'NADYA BUDI SALSABILLA',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14452',
                'name' => 'RAFLY MAULANA ISMAIL',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14453',
                'name' => 'RIKI SAPUTRA ANWAR',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14454',
                'name' => 'SATA ABRISHAM ALDEKI',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14455',
                'name' => 'SHABRINA',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14456',
                'name' => 'SHAFIRA ALYA PRAYITNO',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14457',
                'name' => 'VERDIANSYAH',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14458',
                'name' => 'WISNU ADITYA PUTRA',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
            [
                'voter_code' => '14459',
                'name' => 'ZIANKA OCTAMELIYA PUTRIE BURHAN',
                'role' => 'student',
                'class' => 'XI REKAYASA PERANGKAT LUNAK',
                'position' => null,
                'status' => 'active',
            ],
        ];

        foreach ($voters as $voter) {
            DB::table('voters')->updateOrInsert(
                ['voter_code' => $voter['voter_code']],
                $voter
            );
        }
    }
}
